<?php
/**
 * IdentityClassification
 *
 * PHP version 7.4
 *
 * @category Class
 * @package  belenka\tracify
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Spec
 *
 * This API allows you to send events to Tracify that originate from your server.
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.7.0-SNAPSHOT
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace belenka\tracify\Model;
use \belenka\tracify\ObjectSerializer;

/**
 * IdentityClassification Class Doc Comment
 *
 * @category Class
 * @description 1: email / personally identifiable data. 2: session_id related data. 3: ip address related data / geo related data. 4: user agent (of the customer).
 * @package  belenka\tracify
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class IdentityClassification
{
    /**
     * Possible values of this enum
     */
    public const NUMBER_1 = 1;

    public const NUMBER_2 = 2;

    public const NUMBER_3 = 3;

    public const NUMBER_4 = 4;

    /**
     * Gets allowable values of the enum
     * @return string[]
     */
    public static function getAllowableEnumValues()
    {
        return [
            self::NUMBER_1,
            self::NUMBER_2,
            self::NUMBER_3,
            self::NUMBER_4
        ];
    }
}


