<?php
/**
 * PurchaseEventDataTest
 *
 * PHP version 7.4
 *
 * @category Class
 * @package  belenka\tracify
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Spec
 *
 * This API allows you to send events to Tracify that originate from your server.
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.7.0-SNAPSHOT
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the model.
 */

namespace belenka\tracify\Test\Model;

use PHPUnit\Framework\TestCase;

/**
 * PurchaseEventDataTest Class Doc Comment
 *
 * @category    Class
 * @description Additional per product add these 3 key-value pairs for every product: ITEM{i}, AMT{i}, QTY{i}  *Example:*   ITEM1: product_1  AMT1: 4,30  QTY1: 2  ITEM2: product_2  AMT2: 8,60  QTY2: 1   Important note regarding the ITEM{i}, QTY{i} and AMT{i} parameters. The index i is 1-based, i.e. it starts with 1.
 * @package     belenka\tracify
 * @author      OpenAPI Generator team
 * @link        https://openapi-generator.tech
 */
class PurchaseEventDataTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test "PurchaseEventData"
     */
    public function testPurchaseEventData()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "origin"
     */
    public function testPropertyOrigin()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "order_id"
     */
    public function testPropertyOrderId()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "currency"
     */
    public function testPropertyCurrency()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "amount"
     */
    public function testPropertyAmount()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }
}
