<?php
/**
 * EventsApiTest
 * PHP version 7.4
 *
 * @category Class
 * @package  belenka\tracify
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Spec
 *
 * This API allows you to send events to Tracify that originate from your server.
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.7.0-SNAPSHOT
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the endpoint.
 */

namespace belenka\tracify\Test\Api;

use \belenka\tracify\Configuration;
use \belenka\tracify\ApiException;
use \belenka\tracify\ObjectSerializer;
use PHPUnit\Framework\TestCase;

/**
 * EventsApiTest Class Doc Comment
 *
 * @category Class
 * @package  belenka\tracify
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class EventsApiTest extends TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test case for eventsApiV1CreateEvent
     *
     * Submit new server-side events.
     *
     */
    public function testEventsApiV1CreateEvent()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }
}
